SERIAL_PORT = '/dev/ttyUSB0'
SERIAL_BAUD = 9600

DB_HOST = 'localhost'
DB_PORT = 3306
DB_USER = 'petfeeder'
DB_PASSWORD = 'petfeeder123'
DB_NAME = 'petfeeder'

HUMIDITY_THRESHOLD = 70
FEED_WINDOW_SECONDS = 3600

FLASK_HOST = '0.0.0.0'
FLASK_PORT = 5000
FLASK_DEBUG = False
